import {
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

/**
 * `scenarios/` layout:
 *
 * ```
 * scenarios/
 *   index.html                     landing page — nav across every group
 *   utilities/<slug>/index.html     one utility's static SVG cases
 *   utilities/<slug>/<case>.svg
 *   utilities/<slug>/_meta.json
 *   actions/<slug>/index.html       one action's interactive cases (single page)
 *   actions/<slug>/_meta.json
 * ```
 *
 * Test-only; the whole directory is gitignored and wiped before each run.
 */
export const SCENARIOS_DIR = "scenarios";
const UTILITIES = "utilities";
const ACTIONS = "actions";

/** One-liner shown under a utility group on the landing page. */
const BLURB: Record<string, string> = {
  arrow: "Styled SVG arrows — routes through hex centres, plus 2-hex jump arcs.",
  "line-coverage":
    "Every hex a centre-to-centre segment crosses (the supercover line).",
  "loose-ball":
    "looseBall — d6 direction, d6 distance; the ball rolls till a player stops it.",
  movement: "reachableCubes — BFS flood fill within a step budget.",
  pathfind: "pathCubes — shortest obstacle-free hex path via A*.",
  "pixel-range": "pixelRangeCubes — hexes whose centre falls in a pixel circle.",
};

interface Meta {
  label: string;
  blurb: string;
  count: number;
}

const plural = (n: number): string => `${n} case${n === 1 ? "" : "s"}`;

function writeMeta(dir: string, meta: Meta): void {
  writeFileSync(join(dir, "_meta.json"), JSON.stringify(meta));
}

function readMeta(dir: string): Meta | null {
  try {
    return JSON.parse(readFileSync(join(dir, "_meta.json"), "utf8")) as Meta;
  } catch {
    return null;
  }
}

function subdirs(base: string): string[] {
  try {
    return readdirSync(base, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort();
  } catch {
    return [];
  }
}

// --- shared page chrome ------------------------------------------------------

const BASE_CSS = `
  * { box-sizing: border-box; }
  body { font-family: system-ui, -apple-system, sans-serif; margin: 0;
    color: #1a1a1a; background: #fafafa; }
  main { max-width: 1100px; margin: 0 auto; padding: 1.5rem; }
  a { color: #1560c4; }
  .back { display: inline-block; margin-bottom: 1rem; font-size: .85rem;
    color: #666; text-decoration: none; }
  .back:hover { color: #1560c4; }
  h1 { font-size: 1.4rem; margin: 0 0 .25rem; }
  h2 { font-size: 1rem; margin: 1.75rem 0 .75rem; color: #333; }
  .lede { color: #666; margin: .25rem 0 1.25rem; font-size: .9rem; }`;

function page(title: string, extraCss: string, body: string): string {
  return (
    `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8" />\n` +
    `<meta name="viewport" content="width=device-width, initial-scale=1" />\n` +
    `<title>${title}</title>\n<style>${BASE_CSS}${extraCss}\n</style>\n` +
    `</head>\n<body>\n<main>\n${body}\n</main>\n</body>\n</html>\n`
  );
}

// --- landing page ----------------------------------------------------------

const LANDING_CSS = `
  ul.groups { list-style: none; padding: 0; margin: 0; display: grid; gap: .75rem;
    grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); }
  ul.groups li { border: 1px solid #e2e2e2; border-radius: 8px; padding: .8rem 1rem;
    background: #fff; }
  ul.groups a { font-weight: 600; text-decoration: none; font-size: .95rem; }
  ul.groups .count { color: #999; font-size: .75rem; margin-left: .4rem; }
  ul.groups p { margin: .35rem 0 0; color: #666; font-size: .82rem; line-height: 1.4; }`;

function rebuildLanding(): void {
  const groups: Array<[kind: string, heading: string]> = [
    [UTILITIES, "Utility methods"],
    [ACTIONS, "Actions"],
  ];

  const sections: string[] = [];
  for (const [kind, heading] of groups) {
    const base = join(SCENARIOS_DIR, kind);
    const cards = subdirs(base)
      .map((slug) => {
        const meta = readMeta(join(base, slug)) ?? {
          label: slug,
          blurb: "",
          count: 0,
        };
        return (
          `      <li>\n` +
          `        <a href="${kind}/${slug}/index.html">${meta.label}</a>` +
          `<span class="count">${plural(meta.count)}</span>\n` +
          (meta.blurb ? `        <p>${meta.blurb}</p>\n` : "") +
          `      </li>`
        );
      })
      .join("\n");
    if (cards) {
      sections.push(
        `  <section>\n    <h2>${heading}</h2>\n` +
          `    <ul class="groups">\n${cards}\n    </ul>\n  </section>`,
      );
    }
  }

  const body =
    `  <h1>hexa-game scenarios</h1>\n` +
    `  <p class="lede">Hand-authored hex cases, regenerated by <code>npm test</code>.</p>\n` +
    sections.join("\n");

  mkdirSync(SCENARIOS_DIR, { recursive: true });
  writeFileSync(join(SCENARIOS_DIR, "index.html"), page(
    "hexa-game scenarios",
    LANDING_CSS,
    body,
  ));
}

/** Rebuild only the landing page (e.g. from an `afterAll` guard). */
export const refreshLanding = rebuildLanding;

// --- utility group page ---------------------------------------------------

const GROUP_CSS = `
  .gallery { display: flex; flex-wrap: wrap; gap: 1rem; }
  figure { margin: 0; border: 1px solid #e2e2e2; border-radius: 6px; padding: .5rem;
    background: #fff; }
  figcaption { font-size: .8rem; color: #666; margin-bottom: .35rem; }
  figure img { display: block; width: 300px; height: auto; }`;

/**
 * (Re)build a utility group's page from the `.svg` files sitting in
 * `scenarios/utilities/<slug>/`, then refresh the landing page. Called after
 * every {@link writeScenario}; rebuilt from disk so it aggregates across the
 * parallel vitest workers.
 */
export function registerUtilityGroup(slug: string): void {
  const dir = join(SCENARIOS_DIR, UTILITIES, slug);
  let svgs: string[] = [];
  try {
    svgs = readdirSync(dir).filter((n) => n.endsWith(".svg")).sort();
  } catch {
    return;
  }

  const label = slug;
  const figures = svgs
    .map((file) => {
      const name = file.slice(0, -".svg".length);
      return (
        `      <figure>\n        <figcaption>${name}</figcaption>\n` +
        `        <img src="${file}" alt="${name}" />\n      </figure>`
      );
    })
    .join("\n");

  const body =
    `  <a class="back" href="../../index.html">&larr; all scenarios</a>\n` +
    `  <h1>${label}</h1>\n` +
    `  <p class="lede">${BLURB[slug] ?? ""}</p>\n` +
    `  <div class="gallery">\n${figures}\n  </div>`;

  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "index.html"), page(`${label} scenarios`, GROUP_CSS, body));
  writeMeta(dir, { label, blurb: BLURB[slug] ?? "", count: svgs.length });
  rebuildLanding();
}

// --- action group page --------------------------------------------------

/**
 * Drop a pre-rendered action page at `scenarios/actions/<slug>/index.html` and
 * register it on the landing page. The caller owns the page markup (actions are
 * interactive and bespoke); this just files it and records the metadata.
 */
export function registerActionGroup(
  slug: string,
  meta: Meta,
  pageHtml: string,
): void {
  const dir = join(SCENARIOS_DIR, ACTIONS, slug);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "index.html"), pageHtml);
  writeMeta(dir, meta);
  rebuildLanding();
}

/** Wrap an action body in the shared page chrome. */
export function actionPage(
  title: string,
  extraCss: string,
  body: string,
): string {
  return page(title, extraCss, body);
}
